[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.16",
    "openai>=1.74.0",
    "python-dotenv>=1.1.0",
    "streamlit>=1.44.1",
]
