
[server]
port = 5000
address = "0.0.0.0"
maxUploadSize = 200
enableWebsocketCompression = false
enableXsrfProtection = false
enableCORS = false

[browser]
serverAddress = "0.0.0.0"
serverPort = 5000

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
